# Base
FROM python:3.12-slim

# Dépendances système
RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copie requirements et installation
COPY docker/requirements/requirements.web.txt .
RUN pip install --no-cache-dir -r requirements.web.txt

# Copie du code
COPY ./app ./app

# Commande finale : API FastAPI
CMD uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
